# Generated by Django 4.0.4 on 2022-04-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_show_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_room',
            name='Carcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show_room',
            name='Carlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Task.carlist'),
        ),
    ]
