# Generated by Django 4.0.4 on 2022-04-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_show_room_carcount_show_room_carlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='Carcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carlist',
            name='City',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
