# Generated by Django 4.0.4 on 2022-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_show_room_carlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='Show_roomName',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
