# Generated by Django 4.0.4 on 2022-04-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_carlist_show_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_room',
            name='Carlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Task.carlist'),
        ),
    ]
