# Generated by Django 4.0.4 on 2022-04-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_rename_name_show_room_show_roomname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show_room',
            old_name='Show_roomName',
            new_name='Name',
        ),
    ]
