# Generated by Django 4.0.4 on 2022-04-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_rename_show_roomname_show_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_room',
            name='Carlist',
        ),
    ]
