# Generated by Django 4.0.4 on 2022-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_remove_show_room_carlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_room',
            name='CName',
            field=models.CharField(default=0, max_length=20, verbose_name=[('', '---------'), (3, 'BMW X6'), (1, 'Alto'), (2, 'Ertiga')]),
        ),
        migrations.AddField(
            model_name='show_room',
            name='Cprice',
            field=models.IntegerField(default=0, verbose_name=[('', '---------'), (3, 'BMW X6'), (1, 'Alto'), (2, 'Ertiga')]),
        ),
    ]
