# Generated by Django 4.0.4 on 2022-04-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_show_room_cname_show_room_cprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_room',
            name='CName',
        ),
        migrations.RemoveField(
            model_name='show_room',
            name='Cprice',
        ),
    ]
