# Generated by Django 4.0.4 on 2022-04-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_remove_show_room_cname_remove_show_room_cprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_room',
            name='CarName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Task.carlist'),
        ),
    ]
