# Generated by Django 4.0.4 on 2022-04-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0013_show_room_carname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show_room',
            old_name='CarName',
            new_name='Carname',
        ),
    ]
