# Generated by Django 4.0.4 on 2022-04-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0014_rename_carname_show_room_carname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_room',
            name='Carname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.carlist'),
        ),
    ]
