# Generated by Django 4.0.4 on 2022-04-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0017_alter_show_room_carname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show_room',
            old_name='Carname',
            new_name='Cname',
        ),
    ]
